name: first-ci
on: push
jobs:
    unit-test:
        runs-on: ubuntu-latest
        steps:
            - name: welcome message
              run: echo Hello world
            - name: list files
              run: ls 
            - name: Read Content of readme
              run: cat README.md