name: first-ci
on: push
jobs:
    unit-test:
        runs-on: macos-26
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v6
            - name: welcome message
              run: echo Hello world
            - name: list files
              run: ls 
            - name: Read Content of readme
              run: echo ${{ vars.DOCKER_USERNAME }}
